// Home
export const GET_STUDENTS = "GET_STUDENT"
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS"
export const GET_STUDENTS_FAIL = "GET_STUDENTS_FAIL"

// Edit
export const GET_STUDENT = "UPDATE_STUDENT"
export const UPDATE_STUDENT_INIT = "UPDATE_STUDENT_INIT"
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS"
export const UPDATE_STUDENT_FAIL = "UPDATE_STUDENT_FAIL"

// New
export const ADD_STUDENT = "ADD_STUDENT"
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS"
export const ADD_STUDENT_FAIL = "ADD_STUDENT_FAIL"

// Delete
export const GET_STUDENT_DELETE = "GET_STUDENT_DELETE"
export const STUDENT_DELETE_SUCCESS ="STUDENT_DELETE_SUCCESS"
export const STUDENT_DELETE_FAIL ="STUDENT_DELETE_FAIL"

